- README.md
- build.sh
- chart_test.sh
- examples/gke/Dockerfile
- lib/chartlib.sh
I took a stab at #9. This is still a WIP. I need to do more testing.
> Double-check pod readiness for deployments

- .circleci/config.yml
- README.md
- examples/docker-for-mac/my_test.sh
This adds a sample script that can be run as is in the charts repo to test charts.
> Add sample script for Docker for Mac

- lib/chartlib.sh
Fixes an issue https://github.com/helm/charts/pull/7320#issuecomment-416213125
> [fix]: Limits release name to 29 characters.

- README.md
- lib/chartlib.sh
Enable setting different Github address e.g. for Github Enterprise instances
> Use environment variable for Github address

- examples/docker-for-mac/my_test.sh
> pretify docker4mac script

- Dockerfile
- README.md
- build.sh
- examples/docker-for-mac/my_test.sh
- examples/gke/Dockerfile
These changes caused a number of problems for charts CI. If users
need this, they should extend the image.
> Revert permission changes from #13

- lib/chartlib.sh
> use characters before first equals sign for repo name

- Dockerfile
> Ensure yamllint is updated to 1.12.1

- Dockerfile
> Ensure yq is updated to 2.7.0

- Dockerfile
> Ensure helm is updated to v2.11.0

- Dockerfile
> Ensure kubectl is updated to v1.12.2

- Dockerfile
> Ensure Dockerfile uses more modern pip verison, freeze it to 18.1

- README.md
This is a PR for #45. Let's discuss the ideas there, and specific changes needed here?
> Document supported versions, upgrading, and version-specific PRs

- examples/docker-for-mac/my_test.sh
> Fix wrong docker image tag for docker4mac

- examples/docker-for-mac/my_test.sh
- examples/gke/Dockerfile
> Update base images in samples

- examples/kind/.circleci/config.yml
- examples/kind/README.md
- examples/kind/test/ct.yaml
- examples/kind/test/e2e-kind.sh
Add example how to lint and test charts using CircleCi and [kind](https://github.com/kubernetes-sigs/kind)
> Add kind example

- examples/kind/.circleci/config.yml
- examples/kind/test/e2e-kind.sh
Fix #79 by removing `chmod +x kind` from circleci pipeline
> Fix kind example

- pkg/chart/chart.go
> Use anonymous function to avoid defer in loop

- pkg/config/config.go
> Only require validation configs when validation is enabled

- README.md
- tag.sh
> Improve docs on releasing

- pkg/chart/chart.go
> Log values files used

- Dockerfile
* Helm 2.12.3
* kubectl 1.13.2
> Upgrade Helm and kubectl in Docker image

- .circleci/config.yml
- Dockerfile
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
> Bring Go current for CircleCI

- examples/docker-for-mac/my_test.sh
> docker4mac 2.0 has changed cluster name to docker-desktop

- examples/kind/README.md
> Update kind readme to reflect one worker node cluster setup

- README.md
This fixes a minor typo in the readme that could be misleading. I thought there was some linting available for diffs but there isn't.
> Readme update: lint-changed>list-changed

- README.md
> Add badges for build status and license

- e2e-kind.sh
- examples/docker-for-mac/my_test.sh
- examples/kind/README.md
- examples/kind/test/e2e-kind.sh
- examples/kind/test/kind-config.yaml
> Update kind to v0.2.0

- pkg/chart/chart.go
- pkg/util/util.go
- pkg/util/util_test.go
> Trim leading hyphens from names

- .circleci/config.yml
- e2e-kind.sh
- examples/kind/test/e2e-kind.sh
> Fix kind timeout

- README.md
- examples/docker-for-mac/my_test.sh
- examples/gke/Dockerfile
- examples/kind/.circleci/config.yml
- examples/kind/test/e2e-kind.sh
Signed-off-by: Reinhard Nägele <reinhard.naegele@codecentric.de>
> Update readme and examples for v2.3.1 release

- README.md
- examples/docker-for-mac/my_test.sh
- examples/gke/Dockerfile
- examples/kind/.circleci/config.yml
- examples/kind/test/e2e-kind.sh
Signed-off-by: Reinhard Nägele <reinhard.naegele@codecentric.de>
> Prepare release v2.3.2

- pkg/util/util.go
- pkg/util/util_test.go
Should fix issue in https://github.com/helm/charts/pull/12951
> Trim leading invalid chars from names

- README.md
- examples/docker-for-mac/my_test.sh
- examples/gke/Dockerfile
- examples/kind/.circleci/config.yml
- examples/kind/test/e2e-kind.sh
> Prepare release v2.3.3

- .circleci/config.yml
- e2e-kind.sh
- examples/kind/test/e2e-kind.sh
- examples/kind/test/kind-config.yaml
- examples/kind/test/local-path-provisioner.yaml
Update local path prov to use version 0.0.6
> Update local path provisioner version in the example folder

- .circleci/config.yml
- Dockerfile
- examples/docker-for-mac/my_test.sh
- examples/gke/Dockerfile
- examples/kind/.circleci/config.yml
- examples/kind/test/e2e-kind.sh
> Prepare release v3.0.0-beta.1

- .circleci/config.yml
- e2e-kind.sh
- examples/kind/test/e2e-kind.sh
> Update kind, Helm, and Go

- examples/docker-for-mac/my_test.sh
- examples/gke/Dockerfile
- examples/kind/.circleci/config.yml
- examples/kind/test/e2e-kind.sh
> Prepare release v3.0.0-beta.2

- Dockerfile
Signed-off-by: Scott Rigby <scott@r6by.com>
Routine updates
> Bump Alpine to 3.11

- .goreleaser.yml
> Fix ldflags for version

- Dockerfile
- README.md
update HELM_VERSION to v2.16.5
> update helm version

- README.md
- examples/docker-for-mac/my_test.sh
- examples/gke/Dockerfile
- examples/kind/.circleci/config.yml
- examples/kind/test/e2e-kind.sh
> Prepare release v3.0.0-rc.1

- .goreleaser.yml
In my use case, we run the helm chart test on the arm64 platform. So, if we can get 
the binary file from official repo, it'll be great.
Thanks for taking time to review my pull request.
None
None
> Add arm64 into the goarch list

- examples/docker-for-mac/my_test.sh
- examples/gke/Dockerfile
- examples/kind/.circleci/config.yml
- examples/kind/test/e2e-kind.sh
Signed-off-by: Scott Rigby <scott@r6by.com>
> Update docs for v3.0.0

- Dockerfile
- update HELM_VERSION to v2.16.9
- alpine to 3.12
- kubectl to 1.18.6
- YAMALE to3.0.2
- YAML_LINT to 1.24.2
> Update Helm to 2.16.9

- .circleci/config.yml
- Dockerfile
Update to latest helm, kubectl versions
> Bump  helm , kubectl versions

- Dockerfile
Signed-off-by: David Karlsen <david@davidkarlsen.com>
Upgrades to latest helm version
> chore: Upgrade to helm 3.3.1

- README.md
- examples/docker-for-mac/my_test.sh
- examples/gke/Dockerfile
- examples/kind/.circleci/config.yml
- examples/kind/test/e2e-kind.sh
> Update docs and examples for v3.1.0

- README.md
- examples/docker-for-mac/my_test.sh
- examples/gke/Dockerfile
- examples/kind/.circleci/config.yml
- examples/kind/test/e2e-kind.sh
> Update docs and examples for v3.1.1

- Dockerfile
I updates helm version to 3.4.0
> Helm v3.4.0 will now detect if you have the stable and incubator repository configured with the old location and warn you that you need to update your configuration to the new location. 
https://helm.sh/blog/new-location-stable-incubator-charts/
> Update Helm to 3.4.0

- .github/workflows/release.yaml
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/helm/chart-testing/306)
> Skip using action for tagging. Fixes #305

- Dockerfile
Signed-off-by: Ram <1331672+chukka@users.noreply.github.com>
> Bump Versions

- pkg/config/config_test.go
- pkg/config/test_config.json
- pkg/config/test_config.yaml
update reference from master to main in tests
> Update reference from master to main in tests

- README.md
- examples/docker-for-mac/my_test.sh
- examples/gke/Dockerfile
- examples/kind/.circleci/config.yml
- examples/kind/test/e2e-kind.sh
This reverts commit 672e435015bed5dce43dd6c78014258dd6273faa.
> Revert "Updated docs and examples for v3.2.0 (#338)"

- Dockerfile
This PR attempts to fix #347 by updating the dependencies in the Dockerfile.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #347 
I checked each dependency in the Dockerfile and adjusted the arguments to point to the latest release. Is there anything else that needs to be updated?
> Update Dockerfile dependencies

- .github/workflows/ci.yaml
- e2e-kind.sh
Fix the CI
related to https://github.com/helm/chart-testing/pull/348
> Upgrade tools

- Dockerfile
Signed-off-by: gkarthiks <github.gkarthiks@gmail.com>
Upgrades the alpine and curl versions in docker image to fix the security vulnurability
* Alpine Base image has been upgraded to `alpine:3.14` to upgrade the musl lib version
> bump: alpine version and curl for security fix

- .github/workflows/ci.yaml
- Dockerfile
update helm to to release v3.7.2
after that will do a review to make a new release
> update helm to to release v3.7.2

- Dockerfile
- update helm to v3.8.1
forgot to update in the dockerfile
> update helm to v3.8.1

- .github/dependabot.yml
- .github/workflows/ci.yaml
- Dockerfile
- go.mod
- go.sum
- add docker to dependabot config
- update helm to v3.9.2
- update kubectl and helm in the dockerfile
- update indirect dependencies
> Updates to prepare next release

- .github/workflows/ci.yaml
- .golangci.yml
- go.mod
- pkg/util/util.go
> Upgrade to go 120

- Dockerfile
- update tools in container image
> Bump tools (helm and kubectl) in Dockerfile

- Dockerfile
- update tools in container image
> Bump tools (yamllint and yamale) from pypi in Dockerfile

- README.md
- examples/docker-for-mac/my_test.sh
- examples/gke/Dockerfile
- examples/kind/.circleci/config.yml
- examples/kind/test/e2e-kind.sh
Minor update to docs and examples to the latest (v3.7.1) version of Chart Testing
> Update docs and examples for v3.7.1

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- .golangci.yml
- .goreleaser.yml
- ct/cmd/docGen.go
- ct/cmd/install.go
- ct/cmd/lint.go
- ct/cmd/lintAndInstall.go
- ct/cmd/listChanged.go
- ct/cmd/version.go
- pkg/chart/chart.go
- pkg/tool/helm.go
- sync version comments, update actions and update cosign flag
> sync version comments, update actions and update cosign flag

- .goreleaser.yml
- build.sh
> update goreleaser flags

- .github/workflows/ci.yaml
- .golangci.yml
> update golangci and helm

- pkg/tool/kubectl.go
It's much easier to see the order of actions when the events are sorted by lastTimestamp. This adds that flag to the GetEvents function.
> Sort event list

- .github/workflows/stale.yaml
> add stale action

- .github/workflows/stale.yaml
- if pr/issues have the frozen label to not stale/close
> if pr/issues have the frozen label to not stale/close

- README.md
Fixed the link in the readme
None
> docs: updated quay link

- README.md
> chore(docs): missing link to CI icon

- README.md
- examples/docker-for-mac/my_test.sh
- examples/gke/Dockerfile
- examples/kind/.circleci/config.yml
- examples/kind/test/e2e-kind.sh
Prepare new release according to https://github.com/helm/chart-testing?tab=readme-ov-file#releasing
> Prepare release v3.14.0
