Dockerfile
Updated Helm to 2.10.0
Fixed an issue when running helm init inside a container with uid:gid instead of a username:
```
docker run --rm -it -u 112:117 gcr.io/kubernetes-charts-ci/chart-testing:v1.0.3 sh 
/ $ helm init
Creating /.helm
Error: Could not create /.helm: mkdir /.helm: permission denied
```
=> Helm 2.10 and fix permissions

README.md, lib/chartlib.sh
The use case for this is an environment where every change is not
a new release of a chart. When new releases are created the
increment can be checked while development outside a release
does not need to check for it
=> Adding ability to skip version increment check

lib/chartlib.sh
The return values from the individual calls to `lint_chart_with_single_config`
are masked by the other operations in the `lint_chart_with_all_configs`
function.
When `helm lint` reports an error to STDERR but the chart is incorrectly
given a success tick and the exit code of `chart_test.sh` is 0 for
success. An example using `quay.io/helmpack/chart-testing:v1.1.0`:
==> Linting charts/nomad-server
[ERROR] templates/: render error in "nomad-server/templates/nomad-server.yaml": template: nomad-server/templates/nomad-server.yaml:55:28: executing "nomad-server/templates/nomad-server.yaml" at <{{template "fullname...>: template "fullname" not defined
Error: 1 chart(s) linted, 1 chart(s) failed
--------------------------------------------------------------------------------
✔︎ …
=> Return correct exit code when using values files

app/cmd/root.go
The flag wasn't bound to Viper. Setting it would have no effect.
=> Bind debug flag to Viper

pkg/chart/chart.go, pkg/chart/chart_test.go
Mentioned in #54.
I made code changes and added some tests to ensure that this function uses the correct config setting to determine when to validate maintainers.
Please let me know if there's anything that you'd like me to change stylistically or otherwise. I'm happy to make whatever changes are required to get this merged.
=> Fixes validate maintainers bug inside chart.Testing.LintChart

pkg/tool/helm.go
Readiness check should happen before tests are executed. Otherwise
the fails if there are tests and test pods match the label selectors
that identify pods. Since test pods have status Completed, they
cause the readiness check to fail.
=> Fix readiness check

pkg/chart/chart.go
What it says on the tin. 😄I figure it would be best to lint all the values files we know about.
This introduces 9 new errors for the stable charts:
```
$ ct lint --chart-dirs=stable --all | grep ✖︎
✖︎ stable/ethereum > Error waiting for process: exit status 1
✖︎ stable/keycloak > Error waiting for process: exit status 1
✖︎ stable/kibana > Error waiting for process: exit status 1
✖︎ stable/metrics-server > Error waiting for process: exit status 1
✖︎ stable/minecraft > Error waiting for process: exit status 1
✖︎ stable/mission-control > Error waiting for …
```
=> Lint values files in ci directory

pkg/util/util.go, pkg/util/util_test.go
There are charts with very long names which cause namespace and
release names to exceed the max length of 63 characters. We, thus,
need to truncate long names. Truncation is done from the left in
order to preserve build ids and randomly generated suffixes.
=> Truncate names to 63 characters

pkg/chart/chart.go, pkg/chart/chart_test.go
If the root of a repository is used as the chart dir (`.`) and there are non-empty directories or files, an index out of range will be raised.
fixes #72
=> Fix index out of range when files exist in the root of a chart dir

examples/kind/test/e2e-kind.sh
Signed-off-by: André Bauer <monotek23@gmail.com>
* fixes tiller install error in kind example
`Error: error installing: Post https://172.17.0.2:35017/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp 172.17.0.2:35017: connect: connection refused`
* Before the change our pipeline failed as tiller could not be installed: 
https://circleci.com/gh/kiwigrid/helm-charts/337
* after changing the port tiller install works (even when the build still fails):
https://circleci.com/gh/kiwigrid/helm-charts/344
=> set port in .kube/config file to 6433

pkg/chart/chart.go, pkg/chart/chart_test.go, pkg/util/util.go
=> Fix regression in changed chart detection

pkg/chart/chart.go, pkg/chart/chart_test.go, pkg/util/util.go
Fixes a regression introduced in #73 so that chart directories were no longer required to be in a direct subdirectory of configured chart directories.
This caused problems in https://github.com/helm/charts/pull/10830.
cc @munnerz
=> Require charts to be in direct subdirectories of configured charts dirs

examples/kind/.circleci/config.yml, examples/kind/README.md, examples/kind/test/ct.yaml, examples/kind/test/e2e-kind.sh, examples/kind/test/kind-config.yaml
* Use kind release from GitHub instead of 'go get sigs.k8s.io/kind'
* Run ct container with '--network host' to avoid patching kubeconfig
* Create multi-node cluster with one master and three worker nodes
so pods with anti-affinity can be tested
* Improve wait logic to cater for multiple nodes
* Add log statements
* Remote unnecessary 'k8s' remote to avoid confusion
* Extract function for 'docker exec' calls
=> Update kind example

Dockerfile
I think what happened here is that `latest` was built with `docker build .` rather than `build.sh`, and pushed to quay.io. Previously this would have failed when `ct` wasn't found in the build context, but as of a1528a422bebab52029f5014357f2b2a80b7a321 `ct` exists as a directory and is copied without error.
This PR adds a RUN step to ensure that `ct` can execute, causing `docker build .` to fail.
Prevents #113 (close that issue by building with `build.sh` and pushing again)
=> Break docker build if ct is not executable

examples/kind/test/kind-config.yaml
Set kind node to 1 worker, as `host-path` storage provider doesn't work in multi-node
=> Set kind node to 1 worker

pkg/tool/kubectl.go
Before we start the namespace cleanup we try to delete any remaining PV/PVC(s) in the namespace.
=> add deletion of pv and pvcs

examples/kind/test/e2e-kind.sh, examples/kind/test/local-path-provisioner.yaml
=> Update kind cluster example with working local storage for all nodes

Gopkg.lock, Gopkg.toml, pkg/exec/exec.go, pkg/tool/kubectl.go, pkg/util/util.go
After the namespace deletion sometimes the namespace get stuck in the `Terminating` phase forever and we need to use the script from @unguiculus (https://gist.github.com/unguiculus/d915e911ba04f1f97ecea4f617a2eef5) to remove the namespaces.
This PR introduces the same login in the bash script to the chart-testing, when we check if the namespace still exists we apply the logic to force remove the namespace.
note: for example, last week in the Helm Chart CI Cluster we had around 900 namespaces in Terminating phase.
=> force the namespace deletion by updating the finalizers in the namespace obj

.circleci/config.yml, .goreleaser.yml
Addresses warning message during `build.sh` execution:
```
DEPRECATED: `docker.binary` should not be used anymore, check https://goreleaser.com/deprecations#docker-binary for more info.
```
Link: https://goreleaser.com/deprecations/#docker-binary
=> Fix goreleaser docker.binary deprecation notice

pkg/chart/chart.go, pkg/chart/chart_test.go, pkg/util/util.go
This makes it possible to run `ct install --charts ./` from the top level of a chart's directory.
This seems like a pretty straightforward use case for testing changes to a single chart, especially if that chart is in a dedicated source repository.
fixes #101 
=> Handle empty chart path, add Chart type

pkg/tool/account.go, pkg/tool/account_test.go
**Which issue this PR fixes**: 
fixes #136 
=> fix(account): handle invalid repository domain matches

README.md, pkg/chart/chart.go, pkg/chart/chart_test.go, pkg/tool/git.go
- 8709dde729f4648fb2f08ce96e73ac4d3d117193: Renaming `*WorkingTree` to `*WorkTree` is more consistent with the underlying git commands.
- 37e686641554982be48f3222d697f983df3205e6: Now that we use `git worktree`, we should document which git versions work with `ct`.
- d0d57443dd0f2f2402c85986e49754b85c249858: There is an edge case where `ct` will create a new worktree and then not clean it up if execution is cancelled. This causes `ct` to fail on the next run because `git worktree add` errors if the worktree path already exists. Creating a temp directory for each run fixes that and also should prevent the accidental overwrite of a user-managed git worktree. We should handle the cleanup of the temp directory as part of #60 in the future.
**Which issue …
=> Add git version documentation, rename worktree methods, and handle existing worktree

Dockerfile
update helm to version 2.13.1
fixes https://github.com/helm/chart-testing/issues/140
=> update docker image to use helm 2.13.1

.circleci/config.yml, Dockerfile
update golang image on circleci to build chart-testing using golang 1.12.5
=> Update golang on circleci (#146)Update golang on circleci

pkg/tool/kubectl.go
PV are not namespaced so if we delete will delete running disks which will break the tests
=> Remove force delete of pv and improve cleanup logic

pkg/chart/chart.go, pkg/tool/git.go
=> Fix log messages

tag.sh
This is to avoid accidentally tagging the wrong commit if
the wrong branch is checked out.
=> Use latest upstream instead of local branch for tags

pkg/chart/chart.go, pkg/tool/kubectl.go
Helps identifying issues when Helm timeout because pods cannot be created due to errors.
Affected PR: https://github.com/helm/charts/pull/13444
=> Print events on cleanup

pkg/tool/account.go, pkg/tool/account_test.go
=> Consider username and password in repo urls

README.md, examples/docker-for-mac/my_test.sh, examples/gke/Dockerfile, examples/kind/.circleci/config.yml, examples/kind/test/e2e-kind.sh
Updates versions in example docs in order to prepare a new release that would contain changes since `v2.3.3`
There is no formal issue number, but it would resolve an issue reported in [slack](https://kubernetes.slack.com/archives/CHK6WB5R8/p1571917162009500), 
```
vas 07:39
Hey, is there a plan to release a new chart-testing image with a newer version of Helm that contains this fix: https://github.com/helm/helm/pull/5112?
The latest image is 3.3.2, which has Helm 2.13.1, and it appears that this does not have the fix in it.
```
EDIT: Fixes #179 
Apologies if this is jumping the gun on a release, I am not too familiar with your standard process.
=> Prepare release v2.4.0

Dockerfile
Bumps the helm version to `v2.16.1`
This is a followup to #185, where we decided that `v2.16.0` wasn't stable enough and opted to wait until `v2.16.1` was released.
=> Bump helm to v2.16.1

pkg/chart/chart.go, pkg/util/util.go
Using `list-changed` caused a lot of confusion when trying to get the structure/config correct. This PR is to help make it more understood.
=> List changed fixes

examples/kind/test/ct.yaml
helm3 requires the timeout value to have a unit.
Without this, the test results in the following error:
```
Error: invalid argument "800" for "--timeout" flag: time: missing unit in duration 800
```
This PR updates ct config in the kind example. It is needed to pass correct timeout argument to helm3.
=> examples/kind: Add timeout unit in config

pkg/chart/chart.go, pkg/chart/integration_test.go, pkg/chart/test_charts/mutating-deployment-selector/templates/deployment.yaml, pkg/chart/test_charts/mutating-sfs-volumeclaim/templates/service.yaml, pkg/chart/test_charts/mutating-sfs-volumeclaim/templates/statefulset.yaml
Adding support for Helm 3 introduced creating namespaces
because Helm does not do this automatically anymore.
However, a regression was introduced that always creates
namespaces, even if a dedicated namespace is provided via
CLI flag.
=> Don't create provided namespace

.circleci/config.yml, Dockerfile
Helm v3.0.1 lint on my library chart produces nested file error which is fixed in v3.1.0.
=> Update Helm to v3.1.1

ct/cmd/install.go, ct/cmd/lint.go, ct/cmd/lintAndInstall.go, ct/cmd/root.go
* Fix a regression that would cause test results no to be printed on error
* No longer print usage output on error
Fixes: #209
Fixes: #216
=> Fix printing test results on error

etc/chart_schema.yaml
This adds the `apiVersion` as a required field in `Chart.yaml` as per the Helm documentation.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/helm/chart-testing/issues/221
N/a
=> Adding the apiVersion as a required field in the Chart.yaml validation

tag.sh
This reverts commit 5cb2b8c2359e3402a7f4122c2a1acb235a8f30d9 because it
prevented releasing bug fixes for previous versions from non-master
branches.
=> Revert "Use latest upstream instead of local branch for tags (#153)"

.goreleaser.yml, README.md, pkg/config/config.go
The Homebrew formula installs the config files to Homebrew's
etc directory, so we add that to the search locations for config files.
=> Add Homebrew installer

Dockerfile
**What this PR does / why we need it**: Bumps the helm version in the docker image to the latest 3.2.4
**Which issue this PR fixes** : fixes #249 
**Special notes for your reviewer**: This tool is great, thanks!
=> Bump docker image helm verison to 3.2.4

etc/chart_schema.yaml
**What this PR does / why we need it**: Adds the `type` field to the chart schema. This field is generated by `helm create` and is also described in the [documentation](https://helm.sh/docs/topics/charts/#the-chartyaml-file).
**Which issue this PR fixes**: fixes #251 
**Special notes for your reviewer**: `chart-testing` is awesome!
=> Add type field to chart schema

Dockerfile
**What this PR does / why we need it**: This PR bumps the version of the base image, and the tools within it, to their latest versions.
**Which issue this PR fixes**: supersedes #234 
**Special notes for your reviewer**: I notice that #234 has a request for extra testing, so I've built an image that contains #250, #251, and this PR. It's available [here](https://hub.docker.com/layers/smlx/chart-testing/v3.0.0-patch.1/images/sha256-b8f60684a36bd422a1fe9a8e97cf336584118f89f409a4b99114a2945cb1e5c1?context=explore). I've also tested this image [here](https://github.com/amazeeio/charts/runs/949550295) in the chart-testing lint action.
=> Bump docker image versions

etc/chart_schema.yaml
`home` is optional according to Helm's docs: https://helm.sh/docs/topics/charts/
```
home: The URL of this projects home page (optional)
```
Chart.yaml also has optional declaration for dependencies:
```
dependencies: # A list of the chart requirements (optional)
- name: The name of the chart (nginx)
version: The version of the chart ("1.2.3")
repository: The repository URL ("https://example.com/charts") or alias ("@repo-name")
condition: (optional) A yaml path that resolves to a boolean, used for enabling/disabling charts (e.g. subchart1.enabled )
tags: # (optional)
- Tags can be used to group charts for enabling/disabling together
enabled: (optional) Enabled bool determines if chart should be loaded
import-values: # (optional)
- ImportValues holds …
```
=>  Make home URL optional and support dependencies

pkg/util/util_test.go
The old code was incorrect and no longer builds with Go 1.15 when running `go test`.
See the 1.15 release notes here: https://golang.org/doc/go1.15#vet
**Which issue this PR fixes**: n/a
**Special notes for your reviewer**: none.
=> Fix int to string conversion

.goreleaser.yml, README.md
Signed-off-by: Alexander Zigelski <ali@crunchtime.dev>
Congratulations! 🎉 The formula `chart-testing` has been migrated to `homebrew-core` 🍺 
This means that the `homebrew` community will co-author the formula and the formula is even easier to install (via `brew install chart-testing`).
**What this PR does**:
This PR changes the instructions on how to install `chart-testing` on macOS. It also removes the tap configuration from `goreleaser` which prevents your own tap to be updated. The formula will be updated by the Homebrew community (e.g. automatically via `brew bump-formula-pr chart-testing $VERSION` which is triggered automatically by GitLab CI action in one of my private repos).
If you plan to automate `chart-testing` GitHub releases we can also include a GitHub action that …
=> Migrate chart-testing formula to homebrew/core

ct/cmd/install.go, ct/cmd/lint.go, ct/cmd/root.go, pkg/config/config.go
By default, ct prints the config on startup. This can be problematic
because it may contain senstivie data when helm-repo-extra-args contains
passwords. The new flag enables turning off config printing.
=> Add flag for disabling config printing

README.md
Referencing charts-repo-actions-demo in docs should be beneficial for those
looking for more in-depth examples of how to use ct tool.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
Fixes #241
=> Add reference to charts-repo-actions-demo

Dockerfile, ct/cmd/lint.go, go.mod, go.sum, pkg/chart/chart.go, pkg/chart/chart_test.go, pkg/config/config.go, pkg/tool/cmdexecutor.go, pkg/tool/cmdexecutor_test.go
This is an alternative design to #279 which not only support `helm unittest`, but running any command as part of `ct lint`.
@unguiculus mentioned in slack that you would prefer that instead of pulling in additional dependencies.
I think that's totally valid and also solve many issue. When using #279 I noticed for example that it would be nice if I could pass additional parameters to the command. In that case I needed to add `--helm3`.
Given that helm unittest is installed locally or mounted into the chart testing container one could use this to run helm unittest for each chart with this configured in `ct.yaml`:
```
additional-commands:
- helm unittest --helm3 -f tests/*.yaml {{ .Path }}
```
The command is treated as a go template. Like this it's …
=> Support execution of additional commands during ct lint

ct/cmd/root.go, pkg/chart/chart.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/test_config.json, pkg/config/test_config.yaml
Adds a new configuration option that allows a user to exclude deprecated charts from testing.
fixes #261
I was able to validate some of the behavior manually by linting a deprecated chart, unsure about the best approach to automate that testing, perhaps in the integration_test.go tests.
Decided to hold off on implementing for now, as I realize this flag might need to be discussed.
=> Add option to exclude deprecated charts

pkg/chart/chart.go
If directories are deleted from a chart, ct detects them as invalid
chart directories. A log message is printed to stdout which messes up
the regular output. In order to fix this, the message is now logged to
stderr.
*Example:*
```
$ ct list-changed
Directory 'charts/mychart/templates/deleted' is not a valid chart directory. Skipping...
charts/mychart
```
=> Log invalid chart dirs to stderr

pkg/config/config.go, pkg/util/util.go
Usage of filepath vs. path seems to have been pretty random.
With this change, we consistently use filepath which considers
the platform-specific path separator.
=> Consistently use filepath package

go.sum, pkg/config/config.go, pkg/config/config_test.go
=> Introduce environment variable for custom config dir

pkg/exec/exec.go, pkg/tool/helm.go
Helm v3.4.0 logs a warning about URL deprecation which causes semver
parsing to fail. We need to only read stdout and ignore stderr here.
=> Ignore stderr when parsing Helm version

Dockerfile
switch helm stable chart to use the new location.
Update helm2 version to 2.17.0 to switch helm stable chart to use the new location.
**Which issue this PR fixes** *
N/A
N/A
=> Update helm2 version to 2.17.0

etc/chart_schema.yaml
Makes the depednecy.*.repository field optional because when using a local chart there is no repository.
=> chart_schema.yaml - dependency.repository should not be required

README.md, etc/chart_schema.yaml, examples/docker-for-mac/my_test.sh, examples/gke/Dockerfile, examples/kind/.circleci/config.yml, examples/kind/test/e2e-kind.sh, pkg/util/util_test.go, tag.sh
last chart-testing release for helm v2, that contains the last helm v2 bump to use the final helm v2 (2.17.0) which drops the stable repo from the initialization (which was redirected to another URL)
=> Prepare release v2.5.0

Dockerfile
looks like https://kubernetes-helm.storage.googleapis.com/ is not valid anymore and need to update to get.helm.sh
follow up of https://github.com/helm/chart-testing/pull/319
tested and works 
=> fix download path to get helm binary

.github/workflows/ci.yaml, .github/workflows/release.yaml, .goreleaser.yml
Signed-off-by: Tyler Auerbeck <tauerbec@redhat.com>
This PR adds the building and publishing of arm64 images to quay when a release is published.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #342 
This PR adds the publishing of arm64 images as well as amd64 images when a release is published. Because the same `goreleaser` functionality is used in the `ci` workflow, we needed to add the buildx and qemu actions there as well.
When a release is cut, there will now be a few images pushed to quay. For example, given a release of v3.4.5, you would end up with:
- chart-testing:latest-amd64
- …
=> Add arm64 builds

README.md
Just extend docs with common use case of how to test locally developed chart which is not under `charts/` subdirectory.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
Fixes: #138
Tested both commands locally. In theory it may need to the docstrings but I just thought README.md is good enough.
=> Update docs with example using ct with local repo

ct/cmd/install.go, doc/ct_install.md, doc/ct_lint-and-install.md
Add a unit (s == seconds) to the `--helm-extra-args` help message.
The help message for the `--helm-extra-args` config used an example without units,
which caused to fail the next chart-testing run if just copy-pasted.
```
Error: invalid argument "500" for "--timeout" flag: time: missing unit in duration "500"
Error deleting Helm release: Error waiting for process: exit status 1
```
Might be related to newer go versions ? https://github.com/kubernetes/kubernetes/issues/40783
=> fix: add unit to extra arg help message

README.md
**What this PR does / why we need it**: The docker container will use `host` network with no network isolation. That way, `ct install` can connect to k8s cluster running on host's machine.
**Which issue this PR fixes**: fixes #394
=> docs(README): use the host network in docker example

.github/dependabot.yml, .github/workflows/ci.yaml, .github/workflows/release.yaml
- add dependabot to check gh actions
- update helm to v3.8.1
- update kind to v0.12.0
- use git hash instead of the tags for github actions
=> Updates to github actions

pkg/chart/chart.go, pkg/chart/chart_test.go
Fixed excluded-charts not working if chart-dirs had child directories more than one level.
**Which issue this PR fixes** : fixes #311
Signed-off-by: nekottyo <nekottyo@gmail.com>
=> Fix excluded chart when chart-dirs is multi-level

.github/workflows/ci.yaml, .github/workflows/release.yaml, Dockerfile, setup.sh
- updates for helm, kubectl, goreleaser, syft, cosign and kind
- and refactor the way we install the tools for ci/release jobs
=> Refactor install tools for ci/release jobs

pkg/chart/chart.go
When testing the upgrade we should actually install the new version
Old behaviour (installing the same version, not catching the issue with selectors)
```
Testing upgrades of chart 'nri-prometheus => (version: "2.1.2", path: "charts/nri-prometheus")' relative to previous revision 'nri-prometheus => (version: "2.1.1", path: "ct_previous_revision2130172757/charts/nri-prometheus")'...
[...]
>>> helm install nri-prometheus-y2dumyevqw ct_previous_revision2130172757/charts/nri-prometheus --namespace ct --wait --values ct_previous_revision2130172757/charts/nri-prometheus/ci/test-lowdatamode-values.yaml
>>> helm upgrade nri-prometheus-y2dumyevqw ct_previous_revision2130172757/charts/nri-prometheus --namespace ct --reuse-values --wait
```
New Behaviour …
=> FIX: it should upgrade to new version instead of the old one

pkg/chart/chart_test.go, pkg/chart/integration_test.go, pkg/chart/test_charts/mutating-deployment-selector/templates/deployment.yaml, pkg/chart/test_charts/simple-deployment-different-selector/Chart.yaml, pkg/chart/test_charts/simple-deployment-different-selector/README.md, pkg/chart/test_charts/simple-deployment-different-selector/templates/_helpers.tpl, pkg/chart/test_charts/simple-deployment-different-selector/templates/deployment.yaml, pkg/chart/test_charts/simple-deployment-different-selector/values.yaml, pkg/chart/test_charts/simple-deployment/Chart.yaml, pkg/chart/test_charts/simple-deployment/README.md, pkg/chart/test_charts/simple-deployment/templates/_helpers.tpl, pkg/chart/test_charts/simple-deployment/templates/deployment.yaml, pkg/chart/test_charts/simple-deployment/values.yaml
It fixes:
- the integration test "change immutable deployment.spec.selector field". Since the selector was missing from the manifest the upgrade tests was always failing causing a false positive. This is because the required fields changed in `apps/v1` and selector were not added by https://github.com/helm/chart-testing/pull/205
The error always showing before the upgrade was:
```
missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec
```
It adds:
-  integration tests to avoid regression of https://github.com/helm/chart-testing/pull/434. Basically two simple deployment manifests with the second one adding a different selector. The tests differ from the other one since the different selector belongs to a different chart/chartVersion
=> Fix integration tests for upgrade flag

pkg/chart/chart.go, pkg/chart/integration_test.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/test_config.json, pkg/config/test_config.yaml, pkg/tool/kubectl.go
Simple kubectl commands such as get, describe, and logs should return
quickly, but kubectl does not set a timeout on requests by default.
This change sets a 30s timeout by default on such kubectl commands to
ensure that these don't hang forever if the kubernetes API stops
responding, which is quite possible in CI environments where jobs may
cancelled and kubernetes clusters torn down while ct is running.
This timeout value is configurable via the new `kubectl-timeout` option.
Hopefully closes: #332
n/a
=> Set a request timeout on kubectl commands

.github/workflows/ci.yaml, .github/workflows/release.yaml, .golangci.yml, Dockerfile, ct/cmd/install.go, ct/cmd/lint.go, ct/cmd/lintAndInstall.go, ct/cmd/listChanged.go, e2e-kind.sh, go.mod, go.sum, pkg/chart/chart.go, pkg/chart/chart_test.go, pkg/chart/integration_test.go, pkg/config/config.go, pkg/config/config_test.go, pkg/exec/exec.go, pkg/tool/account.go, pkg/tool/account_test.go, pkg/tool/cmdexecutor_test.go, pkg/tool/git.go, pkg/tool/helm.go, pkg/tool/kubectl.go, pkg/util/util.go
- upgrade to go1.19
- update helm to v3.9.3
- add golangci-lint
- fix lints and Replace github.com/pkg/errors dependency with native error wrapping
=> Upgrade go1.19, helm update and add golangci-lint job

pkg/tool/helm.go
Signed-off-by: Sushanta Das <sushanta.das.ju@gmail.com>
On using `helm version --short` resulting in invalid sematic version if the version includes a build part in the version string.
Instead we can use the `helm version --template {{ .Version }}` to get the helm version. Please see the issue for more information about the problem.
fixes https://github.com/helm/chart-testing/issues/467
=> fix: using helm version --short resulting in an invalid semantic versioning

pkg/chart/chart.go, pkg/config/config.go
In some instances `ct` will stall indefinitely if the log output from the containers is too long.  This PR introduces a new configuration option that will disable printing of the container logs.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #471 
I am sure this PR isn't ideal, but I am not really sure how to work around my issue.  I can say for sure that since using my patched version of `ct` where log printing is disabled, I have not had `ct` hang on any job I have ran locally or in a CI job.
=> Add config option to disable printing of container logs

README.md, pkg/config/config.go
It's handy to put all config files in `.ct` instead of `.`
=> add .ct in current working-directory as config directory

pkg/tool/kubectl.go
Exclude stderr (e.g. deprecation warnings) when parsing command output.
**What this PR does / why we need it**: It ensures that warnings or other output that goes to stderr won't be parsed when trying to list deployments, pods, etc. Today, this is not the case, and many  `ct` subcommands will fail in such situations (e.g. when the [gke-gcloud-auth-plugin](https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke) isn't yet installed).
It's possible that the original implementation wanted to include stderr in the output for these commands for a reason, but this feels like a simple oversight.
It's also possible that there are other similar places in the code that require the same modification, so please feel free to update …
=> Fix parsing kubectl output with warnings

pkg/chart/chart.go, pkg/chart/chart_test.go, pkg/tool/git.go
If a targetBranch is not present in the git repository the `ct list-changed` command will fail. The error message for this is not really meaningful.
This PR will validate if the branch exists and throw a error message which the user will understand.
Because the default branch in GitHub changed from `master` to [`main`](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/) this is a common problem users are facing.
I've built the chart-testing and tested it with master branch as follows:
```bash
$ ct list-changed
Error: targetBranch 'master' does not exist
targetBranch 'master' does not exist
```
**Which issue this PR fixes**:
closes #330
- I am not sure if I …
=> feat: verify if targetBranch is present in git repo

ct/cmd/root.go, doc/ct_install.md, doc/ct_lint-and-install.md, doc/ct_lint.md, doc/ct_list-changed.md, pkg/chart/chart.go, pkg/config/config.go, pkg/util/util.go
see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines
The logging between tests is incredibly verbose. Github has a way of collapsing logs into groups. This takes advantage of that feature.
See https://github.com/redpanda-data/helm-charts/actions/runs/5087615217/jobs/9143147560?pr=521#step:15:2372 for an example.
=> add github grouping of log lines

pkg/exec/exec.go
In some cases `kubectl logs ..` was hanging for us. This mainly happened with pods that logged lines with a lot of characters.
The fix of closing both pipes after reading them successfully did the trick and we weren't getting stuck anymore. 
---
**Which issue this PR fixes** *:
There are some closed issue related to this problem:
- https://github.com/helm/chart-testing/issues/332
- https://github.com/helm/chart-testing/issues/471
This is how you can reproduce the stuck kubectl logs:
```sh
git clone git@github.com:ethpandaops/ethereum-helm-charts.git 
cd ethereum-helm-charts
git checkout bbusa/grandine
docker run --rm --network host --workdir /workdir --volume "$HOME/.kube/config:/root/.kube/config:ro" --volume …
```
=> fix for ct install getting stuck when printing logs: close readers when done with reading

Dockerfile
This change improves the quality of the target Dockerfile in order to follow the recommended Docker writing best practices.
Hi!
The Dockerfile placed at "Dockerfile" contains the best practice violation [DL3048](https://github.com/hadolint/hadolint/wiki/DL3048) detected by the [hadolint](https://github.com/hadolint/hadolint) tool.
The smell DL3048 occurs when the pattern used for the label keys does not match the format recommended by official guidelines.
In this pull request, we propose a fix for that smell generated by our fixing tool. We verified that …
=> Fix for Dockerfile smell DL3048

pkg/chart/chart.go
#511 added the BranchExists check, but it used the value of --target-branch while MergeBase used the compound value of --remote/--target-branch
this PR changes BranchExists to use the same value as MergeBase.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #577   #580
=> use the same ref to check branch existance and merge-base calculation

README.md, pkg/tool/helm.go
Since Helm 3.8 the support of OCI registries is no longer experimental and is enabled by default, this means that more and more people will be using registries to store charts. In order to support this type of repository, a small change is needed because OCI registries can't be added like "regular repositories", and need to use a different command "helm registry login".
Therefore, and since it was [already agreed](https://helm.sh/blog/storing-charts-in-oci/) that OCI repositories should start the URL with "oci://" this PR uses the prefix of the repository URL to select the right command to be able to add these type of repositories.
**Special notes for your reviewer**: I didn't added any automation test because didn't find any similar to what already …
=> feat(helm): Add support for OCI chart repositories

code-of-conduct.md, ct/cmd/root.go, doc/ct_install.md, doc/ct_lint-and-install.md, doc/ct_lint.md, doc/ct_list-changed.md, examples/kind/README.md
Because the default branch on GitHub is [`main`](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/) and not longer `master` this should also be the default to chart-testing.
**Which issue this PR fixes**:
fixes #376 
BREAKING CHANGE:
If e.g an action or workflow is not using an explicit specified `target-branch` the job might will fail after this change.
But after this change new users does not have the problem that a wrong branch is used.
For example I was suffering with the error message `exit status 128`- see #330 because the default branch was not `main`.
=> (Breaking change) chore: change default target-branch to main

Dockerfile
This patch bumps the versions of pip, kubectl, helm, and yamllint.
I have run build.sh locally to verify it still builds, and all the tools are present and working at the proper versions when running the image with Docker.
=> feat(docker): Bump dependencies in Dockerfile

pkg/chart/chart.go
**What this PR does / why we need it**: 
Currently `ct install` with `--upgrade` option is broken. It copies the chart into the `ct_previous_revision` directory, and when it executes `helm install ./ct_previous_revision` it fails with the "wrong release name" error:
```
Testing upgrades of chart "chart-name => (version: \"0.0.1\", path: \".\")" relative to previous revision "chart-name => (version: \"0.0.1\", path: \"ct_previous_revision7182718172\")"...
Installing chart "chart-name => (version: \"0.0.1\", path: \"ct_previous_revision7182718172\")" with values file "ct_previous_revision7182718172/ci/test.yaml"...
Error: INSTALLATION FAILED: release name "ct_previous_revision7182718172-hehs72hayw": invalid release name, must match regex …
```
=> Fix for `--upgrade` option

ct/cmd/root.go, doc/ct_install.md, doc/ct_lint-and-install.md, doc/ct_lint.md, doc/ct_list-changed.md, go.mod, go.sum, pkg/chart/chart.go, pkg/chart/chart_test.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/test_config.json, pkg/config/test_config.yaml, pkg/ignore/ignore.go, pkg/ignore/ignore_test.go
use .helmignore when identifying changed charts.
The use of .helmignore is disabled by default (current behaviour) and enabled with `--use-helmignore`
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #530
the FilterFiles function is adapted from https://github.com/helm/helm/blob/main/pkg/chart/loader/directory.go#L46
=> use .helmignore when identifying changed charts

pkg/config/config.go
This should allow defining `helm-extra-set-args` within the config file or as an environment variable.
That flag was introduced by https://github.com/helm/chart-testing/pull/402
I hope this is sufficient, but please tell me if additional changes need to be applied to make this flag as generic as the others.
=> Add missing `helm-extra-set-args` configuration flag

Dockerfile
=> bump alpine and tools

pkg/chart/chart.go, pkg/chart/chart_test.go, pkg/tool/helm.go
The `ct` tool is leveraging the `--reuse-value` values flag that is a bit controversial since it does not leverage the new values in the values.yaml. https://github.com/helm/helm/issues/8085 https://github.com/helm/helm/issues/3957
This causes many pipeline to fail with false positives (each time you add a new default)
Currently, there is available different flags that overcome that issue "--reset-then-reuse-values", however I think it is better to actually use the values that are available instead of rely on a different flag that might be not available in all Helm versions.
=> fix(upgrade): using the values instead of --reuse-values

etc/chart_schema.yaml
The existing rule for validating dependency import-values worked well for either of these two cases:
**1. Importing exports**
```yaml
dependencies:
- name: dep1
version: 0.14.1
repository: oci://myrepo
import-values:
- data
```
**2. Importing child values into the parent**
```yaml
dependencies:
- name: dep1
version: 0.14.1
repository: oci://myrepo
import-values:
- child: default.data
parent: myimports
```
However, it failed on the following valid usecase:
```yaml
dependencies:
- name: dep1
version: 0.14.1
repository: oci://myrepo
import-values:
- data
- child: default.data
parent: myimports
```
Giving the following error:
```
dependencies.0.import-values.1: '{'parent': 'myimports', 'child': 'default.data'}' is not a str. …
```
=> Fix chart_schema.yaml import-values rule

ct/cmd/install.go, doc/ct_install.md, doc/ct_lint-and-install.md, pkg/chart/chart.go, pkg/config/config.go
**What this PR does / why we need it**: Adds an additional option for release name. Allows charts with long names and additional resources that may append more length to the release name to work with kubernetes 63 character limitation. 
**Which issue this PR fixes** : fixes #343 , #734 
=> Add release-name option

ct/cmd/install.go, ct/cmd/lint.go, ct/cmd/lintAndInstall.go, ct/cmd/listChanged.go, pkg/chart/chart.go
**What this PR does / why we need it:**
Allows the usage of `helm-extra-set-args` key from a `ct.yaml` and not just command-line flags. 
Currently, `helm-extra-set-args` is only available as a command-line flag, despite being part of the config object. This does not appear to be documented.
This change sources the value `extraSetArgs` via the `config` object rather than the cmd.Flags() only.
This PR adds the configuration option but it is never used: https://github.com/helm/chart-testing/pull/697
=> Fix `helm-extra-set-args` in YAML configuration
